SPOTIFY_CLIENT_ID: "YOUR_SPOTIFY_CLIENT_ID"
SPOTIFY_CLIENT_SECRET: "YOUR_SPOTIFY_CLIENT_SECRET"
SPOTIFY_USERNAME: "your-spotify-username"
SPOTIFY_USERID: "your-spotify-userid"
GOOGLE_CLIENT_ID: "YOUR_GOOGLE_CLIENT_ID"
GOOGLE_CLIENT_SECRET: "YOUR_GOOGLE_CLIENT_SECRET"
YT_API_KEY: "YOUR_YOUTUBE_API_KEY"
DEBUG: True
DEV_AUTH_EMAIL: "dev@example.com"
REDIS_HOST: "redis"
REDIS_PORT: 6379
SECRET_KEY: "CHANGE_ME"
PYTHON_RAVEN_DSN: ""
JAVASCRIPT_RAVEN_DSN: ""
LOG_FORMAT: "%(asctime)-15s %(name)-10s [%(levelname)s] %(message)s"
BENDER_USE_DM: False
DM_QUEUE_LOW: 999
DM_ABS_LOW: 0
DM_NUM_TRACKS_PER_USER: 0
DM_USER_EXPIRE_SECONDS: 604800
DM_PENALTY: 900
BUNDLES:
    js:
        prefix: 'js/'
        files:
            - jquery-1.10.2.js
            - underscore.js
            - bootstrap.js
            - backbone.js
            - app.js
            - sc.js
    css:
        prefix: 'css/'
        files:
            - bootstrap.min.css
            - font-awesome.min.css
            - app.css
CACHE_BUSTER: 2017-10-20
SMTP_HOST: "smtp.example.com"
SMTP_USER: "user@example.com"
SMTP_PASS: "password"
SMTP_FROM: "andre@example.com"
SOUNDCLOUD_CLIENT_ID: "YOUR_SOUNDCLOUD_CLIENT_ID"
AIRHORN_MAX: 99
AIRHORN_EXPIRE_SEC: 20
AIRHORN_EXPIRE_COUNT: 2
AIRHORN_LIST_MIN_LEN: 5
USE_BENDER: True
FREE_AIRHORN: 99
BENDER_CLUSTERS: True
BENDER_JAMS: True
BENDER_REGIONS:
    - US
BENDER_DISCOVER_PLAYLIST: "3Qx1GjX3Mfz3WE8SBVXzfH"
TOP_TRACKS_REGION: US
MAX_BENDER_MINUTES: 120
LOG_DIR: './play_logs'
OAUTH_CACHE_PATH: './oauth_creds'
HOSTNAME: "localhost:5000"
BENDER_FILTER_TIME: 604800
